### PR TITLE
untrack vendors folder

### PR DESCRIPTION
**Pull request by AlaaAttya**
remove vendors folder from github

### CODE REVIEW

**Comment by alash3al** [comment]
In my opinion, we should keep it, why?
> to avoid the unknown changes in the dependencies, in other words, "we need to freeze the dependencies".

If you have a solution or another opinion, let's discuss it.

**Comment by AlaaAttya** [comment]
@alash3al this is achievable by setting dependencies versions in the https://github.com/alash3al/wsify/blob/master/Gopkg.toml and all the versions are being locked in the "Gopkg.lock". That's why they created the ".lock" and ".toml"

when packages are being installed, the `dep` is going through all the directories and run `dep ensure` which will install the versions locked in the `Gopkg.lock` and will not check for packages updates

**Comment by alash3al** [comment]
Take a look here:

https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory

Go has some issues with package versioning, and Go packages authors have no strict standards in their packages "for versioning", there are many attempts to come over that, but tell now it is a community issue.

I faced that issue in some repos that have only some branches without versioning!, so I started to follow that approach in some of my projects.

Again, Your approach isn't wrong.

**Comment by alash3al** [comment]
For myself, I have no problem removing it, I'm just afraid of "overwriting/deleting" commits/repos, and really that is what happened to me "in some important projects".

For this project, it has small "very small" dependencies, if you really see that we don't need that fear, let's remove it.

Waiting for your opinion :)

**Comment by AlaaAttya** [comment]
@alash3al they stated here `PR diffs will include changes for files under vendor/ when Gopkg.lock is modified` so packages will not get updated as the `.lock` file saves the commit hash for the last installed version "using this commit hash"

for example, content from `.lock` file
```
[[projects]]
  branch = "master"
  name = "github.com/gin-contrib/sse"
  packages = ["."]
  revision = "22d885f9ecc78bf4ee5d72b937e4bbcdc58e8cae"
```

this will always setup the package from this commit hash

**Comment by AlaaAttya** [comment]
@alash3al and for me also no problem for both, but it's better for deployments 👍

**Comment by alash3al** [comment]
There are some important repos I was depending on, at some point in time, I wanted to rebuild the project on another platform, I shocked because that repo got archived and became unavailable :D.

Anyway, the two approaches are valid but we don't need that strict approach here.

Thanks for your PR.

**Pull request merged**
