### PR TITLE
linter changes + makefile + vendored

### PR DESCRIPTION
**Pull request by RO-29**
https://github.com/alash3al/wsify/issues/5

have also added vendor to follow standards plus MakeFile plus linter changes

### CODE REVIEW

**Comment by RO-29** [comment]
Don't be overwhelmed by file changes, most of them are `vendors/` which are auto added on 

`make dep-init` (`make dep-ensure` afterwards)

**Comment by RO-29** [comment]
Also i have few other ideas to improve code plus add tests which i would like to do in another PR

**Comment by RO-29** [comment]
You can run make lint on `master` to see why changes to original files were required

for now i have ignored linter checks where you are ignoring errors but that's for another PR because i need to know how do you handle errors

**Comment by RO-29** [comment]
make lint output on `master`

```
➔ make lint      
go get -v -u github.com/alecthomas/gometalinter
github.com/alecthomas/gometalinter (download)
gometalinter --install
Installing:
  deadcode
  dupl
  errcheck
  gas
  goconst
  gocyclo
  goimports
  golint
  gosimple
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  megacheck
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  unused
  varcheck
  vet
gometalinter --enable-all -D dupl -D lll -D gas -D goconst -D interfacer -D safesql -D test -D testify -D vetshadow --tests --vendor --warn-unmatched-nolint --deadline=10m --concurrency=2 --enable-gc ./...
flags.go:9:2:warning: don't use ALL_CAPS in Go names; use CamelCase (golint)
flags.go:9:2:warning: exported var FLAG_HTTP_ADDR should have comment or be unexported (golint)
flags.go:10:2:warning: don't use ALL_CAPS in Go names; use CamelCase (golint)
flags.go:11:2:warning: don't use ALL_CAPS in Go names; use CamelCase (golint)
flags.go:12:2:warning: don't use ALL_CAPS in Go names; use CamelCase (golint)
flags.go:13:2:warning: don't use ALL_CAPS in Go names; use CamelCase (golint)
flags.go:17:2:warning: exported var VERSION should have comment or be unexported (golint)
flags.go:18:2:warning: don't use ALL_CAPS in Go names; use CamelCase (golint)
flags.go:21:1:warning: exported function InitFlags should have comment or be unexported (golint)
message.go:3:1:warning: comment on exported type Message should be of the form "Message ..." (with optional leading article) (golint)
message.go:11:1:warning: comment on exported method Message.IsUserAllowed should be of the form "IsUserAllowed ..." (golint)
server.go:17:2:warning: comment on exported var WSUpgrader should be of the form "WSUpgrader ..." (golint)
server.go:33:2:warning: comment on exported var Broker should be of the form "Broker ..." (golint)
server.go:37:1:warning: comment on exported function WSHandler should be of the form "WSHandler ..." (golint)
server.go:117:1:warning: comment on exported function PublishHandler should be of the form "PublishHandler ..." (golint)
server.go:133:1:warning: comment on exported function WelcomeHandler should be of the form "WelcomeHandler ..." (golint)
server.go:141:1:warning: comment on exported function InitWsServer should be of the form "InitWsServer ..." (golint)
webhook.go:10:6:warning: exported type Event should have comment or be unexported (golint)
webhook.go:16:1:warning: exported function TriggerWebhook should have comment or be unexported (golint)
server.go:56:18:warning: error return value not checked (defer conn.Close()) (errcheck)
server.go:59:17:warning: error return value not checked (conn.WriteJSON(map[string]string{) (errcheck)
server.go:80:20:warning: error return value not checked (conn.WriteJSON(map[string]string{) (errcheck)
webhook.go:26:19:warning: error return value not checked (resp.Body.Close()) (errcheck)
server.go:134:1:warning: WelcomeHandler is unused (deadcode)
message.go:12:6:warning: "recieve" is a misspelling of "receive" (misspell)
server.go:122:4:warning: "sucess" is a misspelling of "success" (misspell)
server.go:128:3:warning: "sucess" is a misspelling of "success" (misspell)
server.go:38::warning: cyclomatic complexity 17 of function WSHandler() is high (> 10) (gocyclo)
server.go:75:5:warning: ineffectual assignment to stop (ineffassign)
main.go:1::warning: file is not goimported (goimports)
server.go:134:6:warning: func WelcomeHandler is unused (U1000) (megacheck)
make: *** [lint] Error 1
```

**Review by alash3al — APPROVED** [review]
Awesome changes!

- You moved to a package manager
- You renamed some Global Vars
- Normalized some parts of the code

Thanks Man

**Comment by RO-29** [comment]
cool, thanks for accepting the PR. @alash3al 

This should be my first real commit to open source world since I left college.

it feels awesome!

**Comment by alash3al** [comment]
About optimizing the code and normalizing it more and more, then writing test cases, I agree with you.

I think with your contribution we will do more, and with more contributors, we can make wsify a very powerful software.

**Pull request merged**
